### ISSUE TITLE
segfault in Tst/Short/modstd_s.tst (multithreaded only)

### ISSUE THREAD

**Issue by collares** [Singular/Singular#1077]
Tested with 4.2.0p1 and with the latest spielwiese commit, in both cases compiling with `--disable-static --enable-gfanlib`. Does not crash when running with `--cpus=1 --threads=1`. The stacktrace is below.

```
#0  vspace::internals::VMem::deinit (this=0xb3b220 <vspace::internals::VMem::vmem_global>) at vspace.cc:87
#1  0x00000000006d692e in vspace::vmem_deinit () at ../../kernel/oswrapper/vspace.h:408
#2  0x00000000006d795c in kVerify2 (F=0x7fffd48065b8, Q=0x0) at kverify.cc:287
#3  0x00000000006950a1 in jjSYSTEM (res=0x7ffffffe7ec0, args=0x7ffffffe8050) at extra.cc:425
#4  0x0000000000507914 in iiExprArithM (res=0x7ffffffe7ec0, a=0x7ffffffe8050, op=510) at iparith.cc:9416
#5  0x00000000004e1519 in yyparse () at grammar.y:634
#6  0x0000000000516bf9 in iiAllStart (pi=0x7fffd481fea0, 
    p=0x7fffd4871840 "parameter string command; alias list args; parameter def result;  \n    /* test if args[1] is in result */\n    attrib(result, \"isSB\", 1);\n    int i;\n    for (i = ncols(args[1]); i > 0; i--)\n    {\n     "..., t=BT_proc, l=359) at iplib.cc:310
#7  0x0000000000517021 in iiPStart (pn=0x7fffd4870df0, v=0x7fffd48f5fb0) at iplib.cc:416
#8  0x0000000000517679 in iiMake_proc (pn=0x7fffd4870df0, pack=0x0, args=0x7fffd48f5fb0) at iplib.cc:547
#9  0x00000000004ed2b0 in jjPROC (res=0x7ffffffeb1f0, u=0x7fffd48f58b0, v=0x7fffd48f5fb0) at iparith.cc:1628
#10 0x0000000000505529 in iiExprArith2TabIntern (res=0x7ffffffeb1f0, a=0x7ffffffeb310, op=40, b=0x7fffd48f5990, proccall=0, dA2=0xa14780 <dArith2+4992>, at=271, bt=508, dConvertTypes=
    0xa18800 <dConvertTypes>) at iparith.cc:8752
#11 0x0000000000505c6e in iiExprArith2 (res=0x7ffffffeb1f0, a=0x7ffffffeb310, op=40, b=0x7fffd48f5990, proccall=0) at iparith.cc:8894
#12 0x00000000005002ea in jjKLAMMER_PL (res=0x7ffffffeb1f0, u=0x7ffffffeb310) at iparith.cc:7764
#13 0x0000000000507914 in iiExprArithM (res=0x7ffffffeb1f0, a=0x7ffffffeb310, op=40) at iparith.cc:9416
#14 0x00000000004e0bf6 in yyparse () at grammar.y:480
#15 0x0000000000516bf9 in iiAllStart (pi=0x7fffd4874360, 
    p=0x7fffd4865060 "parameter string Command; alias list Arguments; parameter list #;  \n    /* check for errors */\n    if (char(basering) != 0)\n    { ERROR(\"The characteristic must be zero.\"); }\n\n    /* auxiliary variabl"..., t=BT_proc, l=79) at iplib.cc:310
#16 0x0000000000517021 in iiPStart (pn=0x7fffd4873a00, v=0x7fffd4863ae0) at iplib.cc:416
#17 0x0000000000517679 in iiMake_proc (pn=0x7fffd4873a00, pack=0x0, args=0x7fffd4863ae0) at iplib.cc:547
#18 0x00000000004ed2b0 in jjPROC (res=0x7ffffffee520, u=0x7fffd4863a70, v=0x7fffd4863ae0) at iparith.cc:1628
#19 0x0000000000505529 in iiExprArith2TabIntern (res=0x7ffffffee520, a=0x7ffffffee608, op=40, b=0x7fffd4863a00, proccall=0, dA2=0xa14780 <dArith2+4992>, at=271, bt=508, 
    dConvertTypes=0xa18800 <dConvertTypes>) at iparith.cc:8752
#20 0x0000000000505c6e in iiExprArith2 (res=0x7ffffffee520, a=0x7ffffffee608, op=40, b=0x7fffd4863a00, proccall=0) at iparith.cc:8894
#21 0x00000000005002ea in jjKLAMMER_PL (res=0x7ffffffee520, u=0x7ffffffee608) at iparith.cc:7764
#22 0x0000000000507914 in iiExprArithM (res=0x7ffffffee520, a=0x7ffffffee608, op=40) at iparith.cc:9416
#23 0x00000000004e0bf6 in yyparse () at grammar.y:480
#24 0x0000000000516bf9 in iiAllStart (pi=0x7fffd481f8a0, 
    p=0x7fffd486a5a0 "parameter def I; parameter list #;  \n    /* read optional parameter */\n    int exactness = 1;\n    if (size(#) > 0)\n    {\n        /* For compatibility, we only test size(#) > 4. This can be changed to\n"..., t=BT_proc, l=43) at iplib.cc:310
#25 0x0000000000517021 in iiPStart (pn=0x7fffd4836b50, v=0x7fffd4870fb0) at iplib.cc:416
#26 0x0000000000517679 in iiMake_proc (pn=0x7fffd4836b50, pack=0x0, args=0x7fffd4870fb0) at iplib.cc:547
#27 0x00000000004ed2b0 in jjPROC (res=0x7fffffff1850, u=0x7fffd4870f40, v=0x7fffd4870fb0) at iparith.cc:1628
#28 0x0000000000505529 in iiExprArith2TabIntern (res=0x7fffffff1850, a=0x7fffffff1938, op=40, b=0x7fffd4870ed0, proccall=0, dA2=0xa14780 <dArith2+4992>, at=271, bt=275, 
    dConvertTypes=0xa18800 <dConvertTypes>) at iparith.cc:8752
#29 0x0000000000505c6e in iiExprArith2 (res=0x7fffffff1850, a=0x7fffffff1938, op=40, b=0x7fffd4870ed0, proccall=0) at iparith.cc:8894
#30 0x00000000005002ea in jjKLAMMER_PL (res=0x7fffffff1850, u=0x7fffffff1938) at iparith.cc:7764
#31 0x0000000000507914 in iiExprArithM (res=0x7fffffff1850, a=0x7fffffff1938, op=40) at iparith.cc:9416
#32 0x00000000004e0bf6 in yyparse () at grammar.y:480
#33 0x0000000000516bf9 in iiAllStart (pi=0x7fffd481f8a0, 
    p=0x7fffd4871060 " \n    \"EXAMPLE:\";\n    echo = 2;\n    ring R1 = 0, (x,y,z,t), dp;\n    ideal I = 3x3+x2+1, 11y5+y3+2, 5z4+z2+4;\n    ideal J = modStd(I);\n    J;\n    I = homog(I, t);\n    J = modStd(I);\n    J;\n\n    ring R2"..., t=BT_example, l=91) at iplib.cc:310
#34 0x0000000000517fc2 in iiEStart (
    example=0x7fffd4871060 " \n    \"EXAMPLE:\";\n    echo = 2;\n    ring R1 = 0, (x,y,z,t), dp;\n    ideal I = 3x3+x2+1, 11y5+y3+2, 5z4+z2+4;\n    ideal J = modStd(I);\n    J;\n    I = homog(I, t);\n    J = modStd(I);\n    J;\n\n    ring R2"..., pi=0x7fffd481f8a0) at iplib.cc:765
#35 0x000000000053ced4 in singular_example (str=0x7fffd4820320 "modStd") at misc_ip.cc:466
#36 0x00000000004e2f0f in yyparse () at grammar.y:1124
#37 0x00000000004d92bc in main (argc=2, argv=0x7fffffff9a18) at tesths.cc:233
```

**Comment by collares** [comment]
Something changed recently and now the stack trace is the same as in #1083 (updated it above). I am closing this as a duplicate.
