### ISSUE TITLE
segfault generating documentation (when running doc/examples/ncmodslimgb.sing)

### ISSUE THREAD

**Issue by collares** [Singular/Singular#1083]
Might be a duplicate of #1077, I have no idea. Happens on current master, when executing the `ideal I2 = ncmodslimgb(bs);` line in the example. Stack trace:

```
s^7+7*s^6+499/24*s^5+815/24*s^4+227563/6912*s^3+43627/2304*s^2+4461779/746496*s+595595/746496

Program received signal SIGSEGV, Segmentation fault.
vspace::internals::VMem::deinit (this=this@entry=0x138b5c0 <vspace::internals::VMem::vmem_global>) at vspace.cc:87
87          segments[i] = NULL;
(gdb) bt
#0  vspace::internals::VMem::deinit (this=this@entry=0x138b5c0 <vspace::internals::VMem::vmem_global>) at vspace.cc:87
#1  0x00000000006bc0ad in vspace::vmem_deinit () at ../../kernel/oswrapper/vspace.h:408
#2  id_Farey_0 (x=x@entry=0x7fffd02cc5b8, N=N@entry=0x7fffd03a2dc8, r=<optimized out>) at kChinese.cc:363
#3  0x00000000005126db in jjFAREY_ID (res=0x7fffffff2010, u=<optimized out>, v=<optimized out>) at iparith.cc:2126
#4  0x000000000053e285 in iiExprArith2TabIntern (res=res@entry=0x7fffffff2010, a=a@entry=0x7fffffff24d8, op=op@entry=400, b=b@entry=0x7fffffff2548, proccall=proccall@entry=1, 
    dA2=dA2@entry=0x12f6ed0 <dArith2+6288>, at=275, bt=361, dConvertTypes=0x12f3d60 <dConvertTypes>) at iparith.cc:8705
#5  0x000000000053edb6 in iiExprArith2TabIntern (dConvertTypes=<optimized out>, bt=361, at=275, dA2=<optimized out>, proccall=1, b=0x7fffffff2548, op=400, a=0x7fffffff24d8, res=0x7fffffff2010)
    at iparith.cc:8681
#6  iiExprArith2 (proccall=1, b=0x7fffffff2548, op=400, a=0x7265707061727685, res=0x78696e2f3a6e6962) at iparith.cc:8894
#7  iiExprArith2 (res=res@entry=0x7fffffff2010, a=a@entry=0x7fffffff24d8, op=400, b=0x7fffffff2548, proccall=proccall@entry=1) at iparith.cc:8846
#8  0x00000000004f753d in yyparse () at grammar.y:598
#9  0x000000000057ac82 in iiAllStart (pi=pi@entry=0x7fffd081b120, 
    p=0x7fffd08bc060 "parameter ideal I; parameter list #;  \n  int ncores=1;      // default\n  int exactness = 1; // default\n  int sz=size(#);\n\n  if(sz>2)\n  {\n    ERROR(\"wrong optional parameters\");\n  }\n\n  while(sz > 0)\n  "..., t=t@entry=BT_proc, l=52) at iplib.cc:310
#10 0x000000000057b52c in iiPStart (pn=pn@entry=0x7fffd0811f40, v=v@entry=0x7fffd0954b50) at iplib.cc:416
#11 0x000000000057c112 in iiMake_proc (pn=0x7fffd0811f40, pack=pack@entry=0x0, args=0x7fffd0954b50) at iplib.cc:547
#12 0x000000000050f72a in jjPROC (res=0x7fffffff5650, u=0x7fffd0954370, v=0x7fffd0954b50) at iparith.cc:1628
#13 0x000000000053ddf6 in iiExprArith2TabIntern (res=res@entry=0x7fffffff5650, a=a@entry=0x7fffffff5aa8, op=op@entry=40, b=b@entry=0x7fffd0954450, proccall=proccall@entry=0, 
    dA2=dA2@entry=0x12f69c0 <dArith2+4992>, at=271, bt=275, dConvertTypes=0x12f3d60 <dConvertTypes>) at iparith.cc:8752
#14 0x000000000053edb6 in iiExprArith2TabIntern (dConvertTypes=<optimized out>, bt=275, at=271, dA2=<optimized out>, proccall=0, b=0x7fffd0954450, op=40, a=0x7fffffff5aa8, res=0x7fffffff5650)
    at iparith.cc:8681
#15 iiExprArith2 (proccall=0, b=0x7fffd0954450, op=40, a=<optimized out>, res=<optimized out>) at iparith.cc:8894
#16 iiExprArith2 (res=<optimized out>, a=<optimized out>, op=40, b=0x7fffd0954450, proccall=0) at iparith.cc:8846
#17 0x000000000054ac56 in jjKLAMMER_PL (res=0x7fffffff5650, u=0x7fffffff5aa8) at iparith.cc:7764
#18 0x000000000053cdc9 in iiExprArithM (res=res@entry=0x7fffffff5650, a=a@entry=0x7fffffff5aa8, op=op@entry=40) at iparith.cc:9416
#19 0x00000000004fce7c in yyparse () at grammar.y:480
#20 0x00000000004e5a22 in main (argc=<optimized out>, argv=<optimized out>) at tesths.cc:233
```

**Comment by collares** [comment]
Filed https://github.com/rbehrends/vspace/pull/1, but I will leave this open as a reminder to upgrade vspace in case the PR is accepted.

**Comment by collares** [comment]
@hannes14 Thank you for implementing this in 4.2.0p2! Closing.

**Comment by jankoboehm** [comment]
This is still failing in the Sage CI job in the Singular repo (while building docu examples), see https://github.com/Singular/Singular/actions/runs/34800373612/job/103857631885. It is caused by a race condition in vspace.
