### ISSUE TITLE
Segfault in liftstd

### ISSUE THREAD

**Issue by zickgraf** [Singular/Singular#1111]
The attached test case leads to a segfault with the following backtrace in a debug build:
```
#0  0x00007ffff7a6fb2c in _p_LmTest (p=0x5, r=0x7fffd2c29030, level=0) at ../../../../libpolys/polys/pDebug.cc:324
#1  0x00007fffd49c2ab8 in p_Minus_mm_Mult_qq__FieldQ_LengthFour_OrdGeneral (p=0x7fffd2bb7300, m=0x5, q=0x7fffcf4f76f8, Shorter=@0x7fffffff690c: 32767, 
    spNoether=0x0, r=0x7fffd2c29030) at ../../../../libpolys/polys/templates/p_Minus_mm_Mult_qq__T.cc:23
#2  0x00007ffff7a75aa4 in p_Minus_mm_Mult_qq (p=0x7fffd2bb7300, m=0x5, q=0x7fffcf4f76f8, lp=@0x7fffcf4d016c: 1, lq=1, spNoether=0x0, r=0x7fffd2c29030)
    at ../../../../libpolys/polys/monomials/p_polys.h:1034
#3  0x00007ffff7a7776b in kBucket_Minus_m_Mult_p (bucket=0x7fffcf4d00f0, m=0x5, p=0x7fffcf4f76f8, l=0x7fffffff6a18, spNoether=0x0)
    at ../../../../libpolys/polys/kbuckets.cc:773
#4  0x00007ffff7e4c907 in lazyComp (A=0x7fffffff6ad0, M=0x7fffffff7a70, T=0x7fffffff8a10, index=576, s=0x7fffd2bb7300, l=0x7fffffff6a64, 
    tailR=0x7fffd2c29030) at ../../../../kernel/GBEngine/kLiftstd.cc:133
#5  0x00007ffff7e4cc1b in redLiftstd (h=0x7fffd4b62438, strat=0x7fffd4b62390) at ../../../../kernel/GBEngine/kLiftstd.cc:193
```

[min_case_comm_segfault.txt](https://github.com/Singular/Singular/files/6885177/min_case_comm_segfault.txt)

(Sorry for the large example, this is a simplified homalg dump and I could not minimize it further :-( On my PC, the segfault occurs after some seconds in a regular build, but only after about 5 minutes in a debug build.)

**Comment by hannes14** [comment]
fixed with https://github.com/Singular/Singular/commit/81f53c0542b743d1d5c50c1de444c5451cf4c6ba

**Comment by zickgraf** [comment]
Thanks for the quick fix! No wonder that I could not find a more minimal example, if the segfault occured due to the size of the Gröbner basis :D
